name: Android Build

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
   Android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxpkg --quiet
          haxelib run hxpkg install
          
      - name: Configure Android
        run: |
          haxelib run lime setup android
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Cache ASTC Textures
        id: cache-astc
        uses: actions/cache@v4
        with:
          path: astc-textures
          key: ${{ runner.os }}-astc-${{ hashFiles('astc-compression-data-*.json') }}
          restore-keys: |
            ${{ runner.os }}-astc-

      - name: Run ASTC Compressor
        if: steps.cache-astc.outputs.cache-hit != 'true'
        run: |
          if [ -f "./astc-compression-data-assets.json" ]; then haxelib run astc-compressor compress-from-json -json ./astc-compression-data-assets.json; fi
          if [ -f "./astc-compression-data-content.json" ]; then haxelib run astc-compressor compress-from-json -json ./astc-compression-data-content.json; fi

      - name: Compile
        run: haxelib run lime build android -final -D DLC -D SKIP_ASTC

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Android-Release
          path: export/release/android/bin/app/build/outputs/apk/*
          if-no-files-found: error
