name: Android Build

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
   Android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxpkg --quiet
          haxelib run hxpkg install
          
      - name: Configure Android
        run: |
          haxelib run lime setup android
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Optimize PNG
        run: |
          sudo apt-get update && sudo apt-get install -y optipng
          find assets/ -name "*.png" | xargs -P 0 -I {} optipng -o2 -quiet {}
          
      - name: Optimize Audio Bitrates
        run: |
          sudo apt-get install -y ffmpeg
          find assets/ -name "*.ogg" -exec ffmpeg -i {} -map 0:a -b:a 112k -y {}.tmp && mv {}.tmp {} \; || true

      - name: Compile
        run: |
             haxelib run lime build android -final -ONLY_ARM64 -D DLC -D no-debug

      - name: Create ZIP File
        run: |
          7z a -tzip -mx=9 Android-Release.zip export/release/android/bin/app/build/outputs/apk/release/*.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android Release
          path: Android-Release.zip
          if-no-files-found: error
