name: iOS Build
on: workflow_dispatch

jobs:
  Build:
    runs-on: macos-23
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib install hxpkg --quiet
          haxelib run hxpkg install --force

      - name: Compile iOS
        run: haxelib run lime build ios -release

      - name: Create Ipa
        run: |
          cd export/release/ios/build/*-ios
          mkdir -p Payload
          mv *.app Payload
          zip -r sus.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: iOS-Release
          path: export/release/ios/build/Release-ios/*.ipa
          if-no-files-found: error
