name: iOS Build
on: workflow_dispatch

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Libraries
        run: |
          haxelib path hxpkg > /dev/null 2>&1 || haxelib install hxpkg --quiet
          haxelib run hxpkg install --force
          haxelib remove lime
          haxelib git lime https://github.com/PsychEngine-report/lime-FOR-NMV master

      - name: Compile iOS
        run: haxelib run lime build ios -release -nosign -D DLC

      - name: Making ipa file
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/ImpostorLegacy.app
          ldid -S../../../ImpostorLegacy/ImpostorLegacy.entitlements ImpostorLegacy
          cd ..
          mkdir Payload
          mv ImpostorLegacy.app Payload
          zip -r ImpostorLegacy.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: iOS-Release
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
