name: iOS Build
on: 
  workflow_dispatch:
  workflow_call:

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Libraries
        run: |
          haxelib path hxpkg > /dev/null 2>&1 || haxelib install hxpkg --quiet
          haxelib run hxpkg install --force

      - name: Cache ASTC Textures
        id: cache-astc
        uses: actions/cache@v4
        with:
          path: astc-textures
          key: ${{ runner.os }}-astc-${{ hashFiles('astc-compression-data-*.json') }}
          restore-keys: |
            ${{ runner.os }}-astc-

      - name: Run ASTC Compressor
        if: steps.cache-astc.outputs.cache-hit != 'true'
        run: |
          if [ -f "./astc-compression-data-assets.json" ]; then haxelib run astc-compressor compress-from-json -json ./astc-compression-data-assets.json; fi
          if [ -f "./astc-compression-data-content.json" ]; then haxelib run astc-compressor compress-from-json -json ./astc-compression-data-content.json; fi

      - name: Compile iOS
        run: haxelib run lime build ios -release -nosign -D DLC -D SKIP_ASTC
      
      - name: Making ipa file
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/ImpostorLegacy.app
          ldid -S../../../ImpostorLegacy/ImpostorLegacy.entitlements ImpostorLegacy
          cd ..
          mkdir Payload
          mv ImpostorLegacy.app Payload
          zip -r ImpostorLegacy.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: iOS-Release
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
