name: Mobile Release

on: workflow_dispatch

jobs:
  android:
    uses: ./.github/workflows/android.yml
  ios:
    uses: ./.github/workflows/ios.yml

  Publish:
    needs: [android, ios]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android
        uses: actions/download-artifact@v4
        with:
          name: Android-Release
          path: ${{github.workspace}}

      - name: Download iOS
        uses: actions/download-artifact@v4
        with:
          name: iOS-Release
          path: ${{github.workspace}}

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          prerelease: false
          automatic_release_tag: 'v1.0.0'
          title: 'Impostor Legacy Mobile Port'
          files: |
            ${{github.workspace}}/**/*.apk
            ${{github.workspace}}/**/*.ipa
